package lexer;

public enum TokenType {
    // PALABRAS RESERVADAS DE MINECODE
    CRAFTING_TABLE, END_PORTAL, REDSTONE_IF, SLIME_ELSE, 
    PISTON_LOOP, ENCHANT_FUNC, NETHER_RETURN, TORCH_ON, TORCH_OFF,
    
    // PALABRAS RESERVADAS ORIGINALES (opcionales)
    VAR, PRINT,
    
    // LITERALES
    NUMBER, STRING_LITERAL, IDENTIFIER,
    
    // OPERADORES
    PLUS, MINUS, MULTIPLY, DIVIDE, ASSIGN, EQUALS, NOT_EQUALS,
    LESS, GREATER, LESS_EQUAL, GREATER_EQUAL, AND, OR, NOT,
    
    // SÍMBOLOS
    LEFT_PAREN, RIGHT_PAREN, COMMA, SEMICOLON, COLON,
    
    // FIN DE ARCHIVO Y ERROR
    EOF, ERROR
}